# Generated by Django 5.2.4 on 2025-07-06 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('studentform', '0003_registration_registration_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='payment_time',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='registration_id',
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentform.registration'),
        ),
    ]
