# Generated by Django 5.2.4 on 2025-07-06 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_paymentdetail_payment_time_and_more'),
        ('studentform', '0003_registration_registration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentform.registration'),
        ),
    ]
