# Generated by Django 5.2.4 on 2025-07-06 17:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_paymentdetail_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
