# Generated by Django 5.2.4 on 2025-07-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_paymentdetail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
