# Generated by Django 5.2.4 on 2025-07-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_name', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=50)),
                ('student_first', models.CharField(max_length=100)),
                ('student_middle', models.CharField(blank=True, max_length=100, null=True)),
                ('student_last', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
    ]
