# Generated by Django 5.2.4 on 2025-07-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_mobile', models.CharField(max_length=15)),
                ('relation', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('student_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('standard', models.CharField(max_length=10)),
                ('exam', models.CharField(max_length=50)),
                ('base_fee', models.FloatField()),
                ('tax', models.FloatField()),
                ('total_fee', models.FloatField()),
                ('payment_status', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentForm',
        ),
    ]
