# Generated by Django 5.2.4 on 2025-07-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentform', '0002_registration_delete_studentform'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registration_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
